update chart for init-sql init container

diff --git a/dev/charts/gravitino/templates/deployment.yaml b/dev/charts/gravitino/templates/deployment.yaml
--- a/dev/charts/gravitino/templates/deployment.yaml
+++ b/dev/charts/gravitino/templates/deployment.yaml
@@ -46,13 +46,78 @@ spec:
           {{- toYaml . | nindent 8 }}
           {{- end }}
     spec:
-      {{- with .Values.image.pullSecrets }}
+      {{- with .Values.global.imagePullSecrets }}
       imagePullSecrets:
         {{- toYaml . | nindent 8 }}
+      {{- end }}    
+      initContainers:
+      - name: sqlfile
+        image: {{ include "gravitino.image" . }}
+        imagePullPolicy: "{{ .Values.image.pullPolicy }}"
+        command:
+        - sh
+        - -c
+        - |
+          cp -r /root/gravitino/scripts/*  /tmp/scripts/
+        resources:
+          {{- toYaml .Values.initResources | nindent 10 }}
+        volumeMounts:
+          - mountPath: /tmp/scripts/
+            name: scripts-emptydir
+      {{- if .Values.mysql.enabled }}
+      - name: init-mysql
+        image: {{ include "init-mysql.image" . }}
+        imagePullPolicy: "{{ .Values.image.pullPolicy }}"
+        command:
+          - /bin/bash
+          - -c
+          - |
+            while ! mysql -h {{ .Release.Name }}-mysql -u root -e "SELECT 1"; do
+              echo "Waiting for MySQL to be ready..."
+              sleep 2
+            done
+            if [ -z "$VERSION" ]; then
+              echo "ERROR:Please set VERSION"
+              exit 1
+            fi
+            dir="/scripts/mysql"
+            schema_file="$dir/schema-$VERSION-mysql.sql"
+            if [ ! -f "$schema_file" ]; then
+              echo "ERROR:Failed to find schema file $schema_file"
+              exit 1
+            fi
+            upgrade_files=($(ls $dir/upgrade-*-to-$VERSION-mysql.sql 2>/dev/null))
+            if [ ${#upgrade_files[@]} -eq 0 ]; then
+              echo "ERROR:Failed to find upgrade to $VERSION file"
+              exit 1
+            elif [ ${#upgrade_files[@]} -gt 1 ]; then
+              echo "WARN:Find multiple upgrade to $VERSION files,use the first: ${upgrade_files[0]}"
+            fi
+            upgrade_file="${upgrade_files[0]}"
+            echo "Schema file: $schema_file"
+            echo "Upgrade file: $upgrade_file"
+            if ! mysql -h {{ .Release.Name }}-mysql -u root -D gravitino <"$upgrade_file"; then
+              echo "WARNING: Upgrade script failed: $upgrade_file" >&2
+              echo "Continuing with schema script..." >&2
+            fi
+            mysql -h {{ .Release.Name }}-mysql -u root -D gravitino <$schema_file 
+        resources:
+          {{- toYaml .Values.initResources | nindent 10 }}
+        env:
+          - name: MYSQL_PWD
+            valueFrom:
+              secretKeyRef:
+                name: {{ .Release.Name }}-mysql
+                key: mysql-root-password
+          - name: VERSION
+            value: "{{ .Values.mysql.sqlScriptVersion }}"
+        volumeMounts:
+          - mountPath: /scripts
+            name: scripts-emptydir
       {{- end }}
       containers:
         - name: {{ include "gravitino.name" . }}
-          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
+          image: {{ include "gravitino.image" . }}
           imagePullPolicy: {{ .Values.image.pullPolicy | quote }}
           command:
             - "/bin/bash"
@@ -108,6 +173,8 @@ spec:
         - name: gravitino-conf
           configMap:
             name: {{ include "gravitino.fullname" . }}
+        - emptyDir: {}
+          name: scripts-emptydir    
         {{- if not .Values.persistence.enabled }}
         - name: storage
           emptyDir: {}
